import { NextRequest, NextResponse } from "next/server";
import {
  verifyMessage,
  isAddress,
} from "viem";

export async function POST(
  req: NextRequest
) {
  try {
    const body = await req.json();

    const {
      address,
      signature,
      message,
    } = body;

    if (
      !address ||
      !isAddress(address) ||
      !signature ||
      !message
    ) {
      return NextResponse.json(
        {
          error:
            "Address, signature and message are required.",
        },
        { status: 400 }
      );
    }

    const nonce =
      req.cookies.get(
        "arc_pay_nonce"
      )?.value;

    if (!nonce) {
      return NextResponse.json(
        {
          error:
            "Verification expired. Please try again.",
        },
        { status: 401 }
      );
    }

    /*
     * The message must contain the nonce that
     * was generated by our server.
     */
    if (
      !message.includes(nonce)
    ) {
      return NextResponse.json(
        {
          error:
            "Invalid verification message.",
        },
        { status: 401 }
      );
    }

    const valid =
      await verifyMessage({
        address,
        message,
        signature,
      });

    if (!valid) {
      return NextResponse.json(
        {
          error:
            "Wallet signature is invalid.",
        },
        { status: 401 }
      );
    }

    const response =
      NextResponse.json({
        authenticated: true,
        address:
          address.toLowerCase(),
      });

    /*
     * Consume the nonce so the same signature
     * cannot be reused.
     */
    response.cookies.set(
      "arc_pay_nonce",
      "",
      {
        httpOnly: true,
        secure:
          process.env.NODE_ENV ===
          "production",
        sameSite: "lax",
        path: "/",
        maxAge: 0,
      }
    );

    return response;
  } catch (error) {
    console.error(error);

    return NextResponse.json(
      {
        error:
          "Wallet verification failed.",
      },
      { status: 500 }
    );
  }
}
